### ISSUE TITLE
# of Open Files

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#136]
in dependency with LimitedMemoryStore

**Comment by rrayst** [comment]
probably connected to <webServer>

on windows, you can probably look at how many file handles are currently allocated by java by using Process Explorer https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx

**Comment by xorpherion** [comment]
Checked the```<webserver>``` interceptor and looked at the file handles with Process Explorer. The Webserver was started like this:
```
    <serviceProxy port="7000">
         <webServer docBase="C:\Users\Predic8\Downloads" generateIndex="true" />
     </serviceProxy>
```
This points to my download folder and i started downloading files while watching the file handles. Every file handle that was opened was closed when the download completed.
