### ISSUE TITLE
STATISTICSJDBC: Case sensitve table names

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#143]
Ismail Köksal wrote:

Hi,

Oracle normally is not case sensitive but in DatabaseMetaData.class  is case sensitive. So each time Membrane try to create a table but oracle says its already created and throws exception.

I change the JDBCUtil

 public static boolean tableExists(Connection con, String table) throws SQLException {
        DatabaseMetaData meta = con.getMetaData();
        String [] tables= {"TABLE"};
        ResultSet rs = meta.getTables("", null, "%", a);
        Set<String> tables=new TreeSet<String>(String.CASE_INSENSITIVE_ORDER);
        while (rs.next()) {
                tables.add(rs.getString(3));
            }
        return tables.contains(table);
    }

It works successfully for mysql, oracle, postgres 

See:
https://groups.google.com/forum/#!topic/membrane-monitor/hj0IInRZ1lw

**Comment by xorpherion** [comment]
Did tests before and after + some "investigation". Did the change
