### ISSUE TITLE
ADMIN: Footer

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#144]
Is:

Copyright ©2009-2013 predic8 GmbH. All Rights Reserved. See http://membrane-soa.org/esb/ for documentation and updates.

Should:

Copyright ©2009-2014 predic8 GmbH. All Rights Reserved. See http://www.membrane-soa.org/service-proxy/ for documentation and updates.

**Comment by r41d** [comment]
turn of the year is now permanently taken care of ;)
