### ISSUE TITLE
SSLHandshakeException using a Proxy Config

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#145]
See:

https://groups.google.com/forum/#!topic/membrane-monitor/Q53ewuB6ZFg

Hi,

More news today.
I've try to make a test with a java core batch in the same context (same server, same proxy...) :

        public static void main(String[] args) throws Exception {

        CloseableHttpClient httpclient = HttpClients.createDefault();

        try {

        HttpHost target = new HttpHost("www.google.de", 443, "https");

        HttpHost proxy = new HttpHost("gateway.xxxx.zzzzz.net", 80, "http");

        RequestConfig config = RequestConfig.custom().setProxy(proxy).build();

        HttpGet request = new HttpGet("/");

        request.setConfig(config);

        CloseableHttpResponse response = httpclient.execute(target, request);

        try {

        System.out.println(response.getStatusLine());

        EntityUtils.consume(response.getEntity());

        } 

        } 

        }

--> It's work : HTTP/1.1 200 OK

If I switch "http" by "https" in this line 

    HttpHost proxy = new HttpHost("gateway.xxxx.zzzzz.net", 80, "https");

 
I get the same error than with membrane :

    Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake [...]

--> It's sounds like membrane try to access to my proxy server with HTTPS protocol instead HTTP.

Do you know how can I force membrane to access to my proxy with HTTP protocol ?

Best Regards.

**Comment by malsmith-cs** [comment]
Any update on a fix for this - I'm experiencing the same situation.  We are trying to reverse proxy from a local url (on membrane) to a public https service through a corporate web proxy "firewall"

**Comment by malsmith-cs** [comment]
I went ahead and implemented the proposed fix above, which is working for me in a client's locked down corporate network.    Attached is git diff/patch file with the changes.  
[enable_ssl_via_proxy_connect.diff.zip](https://github.com/membrane/service-proxy/files/418254/enable_ssl_via_proxy_connect.diff.zip)

**Comment by predic8** [comment]
Hi @malsmith-cs,
thanks for the patch. Could you generate a pull request based on your patch?

**Comment by malsmith-cs** [comment]
I could do that - should I post that against the latest master branch?  My changes were done against 4.0.19 because that is was "production" for us.  Either is fine with me.

**Comment by rrayst** [comment]
@malsmith-cs I planned to implement support as described in my comment above. The tests are already completed. A little bit of refactoring in the `core` module is required to cleanly implement all 4 cases. Let me take the diff as a basis. Thanks!

**Comment by malsmith-cs** [comment]
@rrayst 
Ok - even better, please use my diff/patch in any way you see fit.  Consider this my full and complete release of the code/changes.   I look forward to your final & test covered, changes!

**Comment by malsmith-cs** [comment]
Change set looks good to me.  You may need to consider the copy right block in this 
https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/samples/sockets/client/SSLSocketClientWithTunneling.java

It's open source but it should have a proper reference for the doTunnelHankshake function.

**Comment by rrayst** [comment]
Thanks @malsmith-cs , you are absolutely correct.

Thanks for pushing us to finally merge a fix. :)

**Comment by saraivamarco** [comment]
I have exactly the same issue here. When do you predict having a new binary release?

**Comment by rrayst** [comment]
4.2.3 has been released.

**Comment by saraivamarco** [comment]
Hi @rrayst , thanks for the quick reply, just checked membrane's download archive and I cannot find that version 4.2.3, the latest I can find is 4.2.2, can you send the link?

Archive: http://www.membrane-soa.org/downloads/archive/router-archive.htm

**Comment by rrayst** [comment]
Hi @saraivamarco . Sorry, the homepage hasn't been updated yet. You can find the release on https://github.com/membrane/service-proxy/releases/tag/v4.2.3 .

**Comment by saraivamarco** [comment]
@rrayst it works now! great! 👍
