### ISSUE TITLE
Cluster must be named Default

### ISSUE THREAD

**Issue by fabiankessler** [membrane/service-proxy#150]
I could live with this current limitation if 
a) it was documented
b) the code would throw with meaningful message

for the documentation: I have found it on the page https://github.com/membrane/service-proxy/tree/master/cli/examples/loadbalancer-multiple-4 in the sentence "The <cluster> elements in the configuration have to have name="Default" at the moment.".

it needs to be updated in the following places:
* http://www.membrane-soa.org/service-proxy-doc/4.0/configuration/reference/cluster.htm
* all other manual pages that contain info about the cluster tag
* I recommend adding an html comment tag to the examples cluster tag, something like "name Default is currently mandatory, see manual"

about the exception:
* if no name is specified, the service does not start with a meaningless error
* if a name is specified, or the tag attribute is added with empty name="", then the service starts, but when running a request against it, it says no node found.

or maybe it's easier to just remove that limitation instead ;-)

**Comment by xorpherion** [comment]
Will have a look at the documentation on membrane-soa.org

**Comment by xorpherion** [comment]
Other parts of the documentation where name is still "Default" will be left as is for now. The clusters name can now be set to any value ( even empty ).
