### ISSUE TITLE
protect XML beautifier against attacks

### ISSUE THREAD

**Issue by rrayst** [membrane/service-proxy#159]

**Comment by predic8** [comment]
Add Ignore DTD option for XML parsing
https://github.com/membrane/xmlbeautifier/blob/master/src/main/java/com/predic8/beautifier/XMLBeautifier.java

**Comment by xorpherion** [comment]
Added property for XMLInputFactory to disable DTD support
[Commit in XMLBeautifier](https://github.com/membrane/xmlbeautifier/commit/139053f62475dae2285e3afef00e3e7977abad27)
