### ISSUE TITLE
Design change : SLF4J as logging facade, remove dependency to Log4J

### ISSUE THREAD

**Issue by vlk32** [membrane/service-proxy#167]
Hi all, 

I would like to switch logging from Log4J to SLF4J facade and also replace Log4J implementation to Logback for command line implementation.
# Reasons
## Reasons for SLF4J :
- SLF4J is logging facade similar to commons-logging, but with binding at "compile time"
  look at http://jayunit100.blogspot.sk/2013/10/simplifying-distinction-between-sl4j.html ( I had a big classloading issues with embedded commons-logging library in WebSphere AS )
- Nowadays a lot of projects is moving from commons-logging to SLF4J.
- Using only SLF4J as logging facade brings developer possibility to simple choose own logging implementation ( logback, log4j, java.util.logging, ... ), so it simplifies embedding.
- Better logging api for example : 
  
  ```
  LOG.warn("This is param1= {} and param2 = {}", p1, p2)
  ```
## Reasons for Logback :
- http://logback.qos.ch/reasonsToSwitch.html
- The best for me is : automatic configuration reload
# Current state :
- most of classes / libraries uses "commons-logging"
- some of classes uses log4j Logger/LogManager ( but it can be easilly replaced by "commons-logging" )
- only few classes contains access to direct log4j implementation
  - osgi.CoreActivator => load log4j configuration
  - osgi.extended.OsgiAdapter => Adapts Membrane's log4j to the logging of the OSGi container.
  - IDEStarter => load log4j configuration, used only for start from IDE/Eclipse
  - DistributionExtractingTestcase => load log4j configuration, used only for integration test
  - AdminPageBuilder => print log setup in webadmin console
  - DynamicAdminPageInterceptor => change
# Desing
- via maven-enforcer-plugin disable dependecies to commons-logging.jar and log4j.jar
- replace log4j.properties with logback.xml or logback-test.xml
- add compile dependency to slf4j-api, jcl-over-slf4j, log4j-over-slf4j
- add test dependency to logback for modules annot, core, test
- add compile dependency to logback for cli, osgi, sar, war
- remove possibility to change logging via webadmin
  - this is not possible to implemenent only with slf4j-api
  - in case of usage logback, there is automatic reload
- second step can be replace "commons-logging" imports with slf4j
# Impacts
## Positive
- add possibility to choose any logging implementation, not only hardcoded log4j
## Negative
- removes possibility to change logging configuration via webadmin console
# Conclusion

Please add the comments on this proposal. If You accept this design change proposal, I can implement it.

**Comment by rrayst** [comment]
Fixed.
