### ISSUE TITLE
Admin Console: <request> <response> are not displayed right

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#169]
![membrane](https://cloud.githubusercontent.com/assets/1932856/5354373/5528c002-7f87-11e4-92d1-fbbb8ccdad36.png)

**Comment by predic8** [comment]
|
Request
 - Rewriter (Description)
 - Validator (Description)
     |

**Comment by rrayst** [comment]
this was probably a bug in one of the initial 4.X versions and has already been fixed.
