### ISSUE TITLE
Should be able to import one schema from another schema when both schemas are embedded in a wsdl

### ISSUE THREAD

**Issue by longsonr** [membrane/service-proxy#182]
If you have multiple schemas embedded in a wsdl file which reference each other via import then membrane fails to start with a NullPointerException. 

This is similar to issue 179 except that in that case there was no schema to import i.e. the testcase was invalid and in this case there is.

I'll attach two testcases 

 * test.ok.wsdl has an internal schema referencing an external schema file via an import. That works OK.
 * test.bad.wsdl has both schemas embedded in the wsdl with an import that has no schemaLocation

If I remove the import from test.bad.wsdl the error message tells me to put it back in, If I specify a schemaLocation as the wsdl file itself i.e. schemaLocation="test.bad.wsdl" the error message tells me that test.bad.wsdl is not a schema file, therefore I think that not specifying the schemaLocation attribute is the correct thing to do. Also, that's what the spring generator I'm getting all this from originally does i.e. it puts the schemas in with imports that have no schemaLocation attribute.

I have some code that fixes this but I don't think it's right. It may help as a starting point though so I've attached that too. There's a patch to soa-model to allow the namespace of the schema to be accessed and then the membrane patch that allows the schema resolver to resolve other schemas internal to the wsdl.

Feel free to use the files as testcases and the patches as a starting point to any fix.

Files are here: http://filebin.net/n6mhl8k4li

**Comment by predic8** [comment]
Thanks for the detailed report. Do not know if we should fix not so common WSDL configuration cause SOAP usage is already decreased.
