### ISSUE TITLE
JSON validation doesn't work when there is too much content

### ISSUE THREAD

**Issue by victorwon** [membrane/service-proxy#183]
JSONValidator uses an old version of jackson-coreutils 1.5, which returns OK if the JSON string contains additional chars behind a valid JSON object. It's been fixed since 1.6 as confirmed in the following link. 

https://github.com/fge/jackson-coreutils/commit/8d08237ebce637a753834e8ecf1655e02766d204

I'm wondering when membrane would update to include this checkup. However, we do need the validation to go through if the content were empty.

**Comment by predic8** [comment]
Try to replace the jackson jar in the lib folder of Membrane. Maybe Membrane works with the newer version. I will create an issue that we update jackson in Membrane 4.1.X.

**Comment by predic8** [comment]
New Issue:
https://github.com/membrane/service-proxy/issues/184
