### ISSUE TITLE
<rewriter>: URLEncode URL after rewriting

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#187]

**Comment by rtclauss** [comment]
I just saw a bug on my system where I pass in spaced paths.  When I submit 
`/stuff/more%20stuff`
it gets transcribed by the proxy to
`/stuff/more stuff`
which fails when calling the backend.  Based on your [group discussion](https://groups.google.com/forum/#!topic/membrane-monitor/bRDXqfa0EKw) both `getPath()` and `getQuery()` should be changed to `getRawPath()` and `getRawQuery()` in URLUtil.java

**Comment by sachingarg123** [comment]
Hi All,

We found one more issue which is regarding Path parameter. you have fixed query parameter decoding but path parameter is still there.

Please replace getPath() to getRawPath(). it will resolve our issue.

**Comment by xorpherion** [comment]
Hello sachingarg123,
i am currently testing a change for getRawPath() but have to fix some other issues before i can continue. I would like to make sure that i am fixing the right thing here:
```
public static String getPathQuery(URIFactory uriFactory, String uri) throws URISyntaxException {
		URI u = uriFactory.create(uri);
		String query = u.getRawQuery();
		String path = u.getRawPath();
		return (path.isEmpty() ? "/" : path) + (query == null ? "" : "?" + query);
	}
```
where u.getRawPath() is
```
public String getRawPath() {
		if(uri != null)
			return uri.getRawPath();
		return path;
	}
```
Is that right?

**Comment by sachingarg123** [comment]
Yes, it is correct, i tested in my local after extending RewriteInterceptor and using java.net.URI getRawPath of my own.
