### ISSUE TITLE
Change xml config Parser to accept negative values 

### ISSUE THREAD

**Issue by r41d** [membrane/service-proxy#188]
FileExchangeStore has a default value of -1 for attribute maxDays.
The parser doesn't support this yet.

**Comment by predic8** [comment]
@xorpherion have a look

**Comment by rrayst** [comment]
This has been fixed, but the config schema file on http://membrane-soa.org/schemas/proxies-1.xsd hasn't been updated yet.

**Comment by rrayst** [comment]
Fixed.
