### ISSUE TITLE
webServer loads files completely into memory

### ISSUE THREAD

**Issue by rrayst** [membrane/service-proxy#201]
and this fails, if the file is larger than the heap size

**Comment by xorpherion** [comment]
in ``ChunkedBody.writeNotRead()`` and ``Body.writeNotRead()``, call chunk.add only if there is a body observer


use 
```
	<router>

		<transport>
			<ruleMatching />
			<dispatching />
			<reverseProxying />
			<userFeature />
			<httpClient />
		</transport>

		<serviceProxy port="8080" name="junit API">
			<webServer docBase="/path/to/some/large/file" />
		</serviceProxy>

	 </router>
```
for testing

**Comment by github-ronk** [comment]
Hi, we are using 4.3.0 and apparently still encountering this issue.   Could you please clarify if it was indeed fixed, and in which version?  Thanks.   [ attn @xorpherion  @predic8 ]

**Comment by rrayst** [comment]
@github-ronk : Do you have a ```<transport>``` in your ```proxies.xml```?

If not, please include the ```<transport>``` as seen [here](#issuecomment-170020278) .

In any case, please make sure that this ```<transport>``` does not have an ```<exchangeStore .../>``` child. (The ```exchangeStore``` reads requests and responses onto the heap, passes them for buffering to an ```*ExchangeStore``` and this makes them available for viewing in the ```adminConsole```. When the the request/response is larger than the free heap space, this fails.)

At the moment, you cannot use the ```adminConsole``` to view requests/responses when you have large ones.

To make sure that you do not get an ```OutOfMemoryError```, either
* disable viewing the requests (by removing ```<exchangeStore .../>```, as described above) or
* use a [```limit```](https://www.membrane-soa.org/service-proxy-doc/4.4/configuration/reference/limit.htm) interceptor to limit the body lengths.

**Comment by github-ronk** [comment]
We do not have a proxies.xml file, we create the router in code:
`
HttpRouter router = new HttpRouter();
`
And then just add a couple of SSL rewriting interceptors...

**Comment by rrayst** [comment]
It`s basically the same thing.

```router.start()``` will implicitly create a new transport, if none has been set so far. Therefore, you need to use

```
HttpTransport transport = new HttpTransport();
transport.getInterceptors().add(new RuleMatchingInterceptor());
transport.getInterceptors().add(new DispatchingInterceptor());
transport.getInterceptors().add(new ReverseProxyingInterceptor());
transport.getInterceptors().add(new UserFeatureInterceptor());
transport.getInterceptors().add(new HTTPClientInterceptor());
router.setTransport(transport);
router.start();
```

(and omit the ```ExchangeStoreInterceptor```, which would also be [auto-created](https://github.com/membrane/service-proxy/blob/711c46a09fbd1baba3ac8f09cbac8a3e05d4e232/core/src/main/java/com/predic8/membrane/core/transport/Transport.java#L62).)

**Comment by github-ronk** [comment]
Will try, thanks a lot!
