### ISSUE TITLE
fix examples/websocket-stomp/proxies.xml

### ISSUE THREAD

**Issue by rrayst** [membrane/service-proxy#210]
and replace it by the one listed on http://www.membrane-soa.org/service-proxy-doc/4.1/websocket-stomp-proxy.htm

and write a test for the example

**Comment by predic8** [comment]
@xorpherion have a look at the example

**Comment by xorpherion** [comment]
I tried using an embedded tomcat and a custom message broadcaster to emulate activeMQ to write the example test ( and discarded that approach ) but maybe you have a better idea @rrayst . Im also not sure how the "subscribe" from the stomp client works and therefore how to emulate it.

**Comment by xorpherion** [comment]
Partial test: a05d3d06e90466aabae19c2404cc4924a1c81173
