### ISSUE TITLE
LoadBalancingInterceptor asks DispatchingStrategy just once

### ISSUE THREAD

**Issue by fabiankessler** [membrane/service-proxy#216]
The DispatchingStrategy only had the chance to define the FIRST node to be used. If that node fails, failover goes ahead and tries the other nodes in the ever same order.

The code for this is in LoadBalancingInterceptor.setFailOverNodes().
This currently adds all alternative nodes in a fixed order.

In most cases this is irrelevant. When is it bad?
If one node is faulty, it causes too much load on the first alternative node. That first node then gets double the load.

If multiple area faulty, it gets worse, it goes through the same chain and the api user may have to wait a long time until a functional node is found.

Possible ways to improve this:
Current method is `Node dispatch(LoadBalancingInterceptor)`
The DispatchingStrategy interface could have a method that returns a list of nodes (by priority) instead of just one. `List<Node> dispatch(LoadBalancingInterceptor)`
Or it could be called again for an alternative node `Node dispatch(LoadBalancingInterceptor, List<Node> exceptTheseThatWereTriedAlready)`

I understand that this is not a big issue. Nodes are supposed to work ... either by fixing them, or disabling them (externally through the API or through the newly suggested FaultMonitoringStrategy).

Still I wanted to leave that info here.

**Comment by rrayst** [comment]
This relates to https://github.com/membrane/service-proxy/pull/214#issuecomment-141920942 .

Feel free to change the load balancing code, not many customers have implemented custom extensions there. (And if they have, they can either migrate or stay on the 4.0.X branch.)

Custom interceptors are much more common, on the other hand.

Therefore, the simplest way is probably
* Get rid of the old failover logic
 * ``List<Node> dispatch(LoadBalancingInterceptor)`` works for that.
* Expose destination failures from the ``HttpClient``
 * if the ``HttpClient`` fails on any destination and retries the next destination, the failure reason is currently discarded. Alter this by storing some kind of log, which destination failed with which reason (maybe by using ``exchange.setProperty()``). Please make sure that the standard fast path (where only one destination exists) does not create too many additional objects.
* Fix the ``LoadBalancingInterceptor``
 * implement ``LoadBalancingInterceptor.handleAbort()`` by calling ``updateDispatchedNode(exc);`` and ``strategy.done(exc);``.
 * call ``n.collectStatisticsFrom(exc);`` only if ``exc.getResponse()`` is not ``null`` (which may be the case when ``handleAbort()`` is invoked)
* Implement your logic
 * enhance ``LoadBalancingInterceptor.handleResponse()`` and ``.handleAbort()`` to extract the failure log from the exchange (if one there is one) and pass it on to your strategy, so it can react and shutdown a failed node.

As this only marginally affects the standard case (no load balancing, only 1 destination), we would be happy to merge requests like this.


(not related: how are nodes coming back up again? :) )
