### ISSUE TITLE
Javascript Interceptor

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#245]
<javascript>
    let x = 1;
    ....
</javascript>

Implicit variables like exchange should be in scope. The Javascript engine should be the one from the Java SDK.

**Comment by xorpherion** [comment]
Added a basic Javascript interceptor

**Comment by xorpherion** [comment]
Added a basic Javascript interceptor

**Comment by xorpherion** [comment]
There is one last problem: The example runs without problems from the IDE ( ran with the IDEStarter ) but doesn't work when run from the distribution ( which is ran from the Starter ). When ran from the distribution some classes aren't found which results in a ScriptException. In the Example it happens at the "Outcome.CONTINUE;" line where the Outcome class isn't found. Any Javascript code before that runs without a problem. So there could be some classpath problem
