### ISSUE TITLE
AdminConsole: /admin works for all ports?

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#251]
Sachin Garg wrote:

I also verified that if i add <adminconsole/> in <serviceproxy> with port and basic auth then it works for that particular port but if hit comes from some other port with url as /admin then also it goes to admin console.

Below is my settings:

<serviceProxy name="Console" port="8009">
           
            <basicAuthentication>
                <user name="admin" password="proxy" />
            </basicAuthentication>
            <adminConsole />
        </serviceProxy>

URl should work like http://localhost:8009/admin

but it is also working for http://localhost:8080/admin (without asking for username/password)

Should be backported to 4.0.X branch also.

**Comment by rrayst** [comment]
this is not the case.

the <web:servletTransport> ignores the "port" attribute, as ports are configured within the web server configuration.
