### ISSUE TITLE
Warn on startup, if limitedMemoryExchangeStore.maxSize > JVM max heap size

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#253]
wrapper starts Membrane with 128 MByte. Membrane is restarted each time the memory is used.
uncomment in wrapper.conf and set value to e.g. 1024 MB

**Comment by rrayst** [comment]
+100MB

**Comment by predic8** [comment]
We leave the 128 MBytes and use the warning instead. Better to use an error instead of a warning an make the log very prominent, so that it will not be overlooked.

**Comment by xorpherion** [comment]
Done.
[https://github.com/membrane/service-proxy/commit/2a02d509ccb6c8764ba53b33df8691484ff9bb0d](url)
