### ISSUE TITLE
fileExchangeStore interceptor not working with chunked transport encoding

### ISSUE THREAD

**Issue by zdenekhrib** [membrane/service-proxy#256]
in service-proxy/core/src/main/java/com/predic8/membrane/core/http/ChunkedBody.java
line "bodyComplete = true;" should be moved from line 101 to 96

otherwise the fileExchangeStore interceptor can not work for chunked transport encoding

**Comment by predic8** [comment]
Thanks we will have a look at it.

**Comment by xorpherion** [comment]
Sorry for the late response. We did some testing and made the change. Thanks
