### ISSUE TITLE
adminConsole is broken (css and js cannot be resolved)

### ISSUE THREAD

**Issue by rrayst** [membrane/service-proxy#262]

**Comment by symle** [comment]
Because of WebServerInterceptor  docBase change (( setDocBase  change )) . It fix schema absulutePath but brokes the css and js

**Comment by xorpherion** [comment]
Hello symle,
this should now be fixed with the latest commit.

**Comment by symle** [comment]
Thanks, it works fine

@rrayst  you can close the issue

**Comment by predic8** [comment]
@symle thanks for your help
