### ISSUE TITLE
Links to SOAP Quickstart, REST Quickstart, and Examples are brok

### ISSUE THREAD

**Issue by helpermethod** [membrane/service-proxy#263]
Hi,

it seems all these links on the main README are broken:

http://membrane-soa.org/esb-doc/current/rest-quickstart.htm
http://membrane-soa.org/esb-doc/current/soap-quickstart.htm
http://www.membrane-soa.org/service-proxy-doc/current/interceptors/examples.htm

**Comment by predic8** [comment]
Danke. Gehen jetzt wieder.

 

Noch eine schöne Zeit

 

 

-- 

predic8 GmbH

Moltkestr. 40

 

53173 Bonn

 

http://predic8.de

Tel: +49 (0) 228 5552576-0

Fax: +49 (0) 228 5552576-50

 

Amtsgericht Bonn

HRB 16152

Geschäftsführer: Thomas Bayer

 

Von: Oliver Weiler <notifications@github.com>
Antworten an: membrane/service-proxy <reply@reply.github.com>
Datum: Dienstag, 12. Juli 2016 um 15:24
An: membrane/service-proxy <service-proxy@noreply.github.com>
Betreff: [membrane/service-proxy] Links to SOAP Quickstart, REST Quickstart, and Examples are brok (#263)

 

Hi,

it seems all these links on the main README are broken:

http://membrane-soa.org/esb-doc/current/rest-quickstart.htm
http://membrane-soa.org/esb-doc/current/soap-quickstart.htm
http://www.membrane-soa.org/service-proxy-doc/current/interceptors/examples.htm
