### ISSUE TITLE
service config can store in database , for instance  redis    mongo?

### ISSUE THREAD

**Issue by ranran472970026** [membrane/service-proxy#272]
Hi,the serivce config infos  in membrance service proxy  write in proxy.xml 。I have many services , so every time I add new service , need  open proxy.xml and config . Membrance can store service config info in redis or mongo ，as I kown ,most service proxy can do it. If I want to store it in mongo，can you give me an idea ？Thank you ，and thanks for your contribution on membrance。

**Comment by keshavarzi** [comment]
Why do you want to store it in Mongo? Yes there are other proxies that can do that. But a Membrane proxy is thanks to the spring integration more powerful than other proxies. A proxy is just a bean. But if you want to you can use the Membrane API and store the proxies somewhere else.

 

Cheers,

Thomas

 

Am 08.09.16, 10:52 schrieb "Dylan.zhang" <notifications@github.com>:

 

Hi,the serivce config infos in membrance service proxy write in proxy.xml 。I have many services , so every time I add new service , need open proxy.xml and config . Membrance can store service config info in redis or mongo ，as I kown ,most service proxy can do it. If I want to store it in mongo，can you give me an idea ？Thank you ，and thanks for your contribution on membrance。
