### ISSUE TITLE
When trying to open a port below 1024..

### ISSUE THREAD

**Issue by DanielBo** [membrane/service-proxy#273]
.. Show a different kind of exception, which indicates it's more likely that you lack the permission to open the port, than the port actually being occupied.

**Comment by rrayst** [comment]
Running Membrane Service Proxy in Docker solves this problem, as docker containers by default have the CAP_NET_BIND_SERVICE capability.

Executing ``setcap cap_net_bind_service=+ep /path/to/java`` once marks the java executable as requiring this capability.
