### ISSUE TITLE
Missing soa-model-core v1.3.0

### ISSUE THREAD

**Issue by owieboy** [membrane/service-proxy#279]
I encountered a failed dependency error when building v4.0.18. 
`Could not resolve dependencies for project org.membrane-soa.service-proxy:service-proxy-core:jar:4.0.18: The following artifacts could not be resolved: com.predic8:soa-model-core:jar:1.3.0, com.springsource:com.springsource.javax.annotation:jar:1.0.0, com.floreysoft:jmte:jar:3.0-p8: Could not find artifact com.predic8:soa-model-core:jar:1.3.0 in predic8-releases (http://repository.membrane-soa.org/content/groups/public)`

https://github.com/membrane/soa-model the oldest tag is 1.3.2.

**Comment by xorpherion** [comment]
Hello owieboy,
as far as i can see there is no other option than to use v4.0.19 and onwards. i just had a quick look at the commit history and found this commit `https://github.com/membrane/service-proxy/commit/95091fc5fd558d1add6de371d0f6f5b5749003ba`
This happened right before v4.0.19 and bumped soa-model-core version to 1.5.0.
Hope i could help you.

**Comment by owieboy** [comment]
Alright, thanks. I encountered this issue while customizing the fileExchangeStore for a requirement in our project. I switched to 4.3.0 and got it working already. Thanks so much.
