### ISSUE TITLE
An empty response body can hang an interceptor

### ISSUE THREAD

**Issue by rossdrew** [membrane/service-proxy#281]
Using Membrane v4.4.1 JAR in a Java project.   If I intercept a request in `handleRequest` and make changes to it's response object (to change the status code) and there is no body, Membrane will hang trying to read the `InputStream`, and seemingly ignore the 'handleResponse' call (if the `Flow` is set to `REQUEST_RESPONSE`).
As the other interceptors are still called, this was very confusing till I stepped through and saw why.

**Comment by rrayst** [comment]
What does your ```handleRequest``` method return? What is the status code before and after your change?

(Have you found https://www.membrane-soa.org/service-proxy-doc/4.4/interceptors.htm ?)

**Comment by rossdrew** [comment]
`handleRequest` is checking against an IdP then setting the 403 to return more useful output to the user.  i.e.

```
Response response = Response.ResponseBuilder.newInstance().status(403, "User not Authenticated").build();

originalExchange.setResponse(response);
```

but if I don't also set the body:-

```
Response response = Response.ResponseBuilder.newInstance().status(403, "User not Authenticated").body(new byte[] {}) .build();
```

Membrane will block while trying to read the input stream of the body without any kind of output.

**Comment by rrayst** [comment]
Not setting a body (as in your ``Response.ResponseBuilder.newInstance().status(403, "User not Authenticated").build()`` example) implicitly sets ``new EmptyBody()`` on the Message.

Therefore, the problem probably lies elsewhere. For example, not reading the response from the target could mess up the HTTP protocol in the Membrane->Target communication.

Please reopen, when more details are available.
