### ISSUE TITLE
CORS requests behave unexpectedly

### ISSUE THREAD

**Issue by rossdrew** [membrane/service-proxy#283]
If a cross origin _OPTIONS_ request is received from a browser, Membrane expects a _content-length_ header or an _EOF_ in the stream but no browsers add these, meaning **all** CORS requests log an [error](https://github.com/membrane/service-proxy/blob/711c46a09fbd1baba3ac8f09cbac8a3e05d4e232/core/src/main/java/com/predic8/membrane/core/http/Message.java#L178) then [fail because the browser also doesn't add an EOF](https://github.com/membrane/service-proxy/blob/711c46a09fbd1baba3ac8f09cbac8a3e05d4e232/core/src/main/java/com/predic8/membrane/core/http/Message.java#L192).

There are [some comments](https://github.com/membrane/service-proxy/blob/711c46a09fbd1baba3ac8f09cbac8a3e05d4e232/core/src/main/java/com/predic8/membrane/core/http/Message.java#L189) mentioning the reason and quoting the HTTP 1.1. spec but [I can't seem to find](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html) the requirement of _content-length_/_EOF_

**Background**
I have an Angular2 page that makes REST requests to my back-end using the _Authorization_ header.  I have inserted Membrane as a reverse proxy which fails on every CORS _OPTIONS_ request, sent from the browser.

**Comment by skeppeler** [comment]
Are you using HTTP 1.0 by any chance?  I have nginx acting as a reverse proxy in front of Membrane and I was running into the same issue until I specified in my reverse proxy that HTTP 1.1 be used.  I don't believe `OPTIONS` was introduced until HTTP 1.1.

**Comment by rossdrew** [comment]
This was a result of a mistake on my part.  I do need to unconditionally let all OPTIONS requests through but had messed up an interceptor later in the chain.
