### ISSUE TITLE
WS-Security integration

### ISSUE THREAD

**Issue by tranca** [membrane/service-proxy#284]
Hi,

I've read the security advantages offered by "service-proxy" and I can see that SSL/TLS encryption is offered to encrypt the exchanges between a client and the server, but I can't find anything about the security of the webservice request/response itself. I'm talking about integrity and identity checks (offered by "WS-Security" for example). 

Is this implemented but not showed on the docs ?

Thanks !

**Comment by predic8** [comment]
We do not offer WSS support directly. But you can route SOAP messages containing WSS elements.
