### ISSUE TITLE
Do not store video/*, audio/* ... in the limitedMemoryStore

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#287]
It is not possible to do anything with these types in the admin UI. So we can ignore:

video/*, 
audio/*,
multipart
application/octet-stream

**Comment by xorpherion** [comment]
The new limited exchange store algorithm is currently opt in and needs testing

**Comment by rrayst** [comment]
Request/response bodies are now truncated by default. Other handling strategies may be configured on the LimitedMemoryExchangeStore.
