### ISSUE TITLE
Question, How to I can change serversocket port?

### ISSUE THREAD

**Issue by marti1125** [membrane/service-proxy#290]
07:07:44,385 ERROR RouterCLI:50 - Failed to start bean 'router'; nested exception is java.lang.RuntimeException: com.predic8.membrane.core.transport.PortOccupiedException: Opening a serversocket at port 80 failed. Please make sure that the port is not occupied by a different program or change your rule configuration to select another one.
org.springframework.context.ApplicationContextException: Failed to start bean 'router'; nested exception is java.lang.RuntimeException: com.predic8.membrane.core.transport.PortOccupiedException: Opening a serversocket at port 80 failed. Please make sure that the port is not occupied by a different program or change your rule configuration to select another one.

I added

```
<serviceProxy port="9001">
    <webSocket/>
    <target host="localhost" port="2001" />
</serviceProxy>

```
but it doesn't work

**Comment by marti1125** [comment]
running in port 80:

```
COMMAND PID         USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
firefox 505 willyaguirre   44u  IPv4 0xbd1ba0557f02e4a5      0t0  TCP 192.168.1.101:63703->client-200.60.136.17.speedy.net.pe:http (ESTABLISHED
```

**Comment by predic8** [comment]
Please post your complete proxies.xml

**Comment by marti1125** [comment]
```
<spring:beans xmlns="http://membrane-soa.org/proxies/1/"
			  xmlns:spring="http://www.springframework.org/schema/beans"
			  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xsi:schemaLocation="http://www.springframework.org/schema/beans
	                    http://www.springframework.org/schema/beans/spring-beans-4.2.xsd
	                    http://membrane-soa.org/proxies/1/ http://membrane-soa.org/schemas/proxies-1.xsd">

	<router>

		<serviceProxy port="2000">
		    <webSocket/>
		    <target host="localhost" port="2001" />
		</serviceProxy>

		<soapProxy wsdl="http://wsdr.test.mc/wsDataRecord.asmx?wsdl">
		</soapProxy>

		<serviceProxy port="2000">
		    <basicAuthentication>
		        <user name="bob" password="secret" />
		    </basicAuthentication>
		    <target host="localhost" port="9000" />
		</serviceProxy>


	</router>
```
I can not put the original wsdl is private =/

**Comment by predic8** [comment]
What is endpoint address inside your WSDL?

**Comment by marti1125** [comment]
@predic8 in gist please :D

**Comment by predic8** [comment]
The proxy:

<soapProxy wsdl="http://wsdr.test.mc/wsDataRecord.asmx?wsdl">
		</soapProxy>

opens the port. Change it in the WSDL if you like.

**Comment by marti1125** [comment]
but the WSDL is not me How to I can change the port in service-proxy?

**Comment by predic8** [comment]
Overwrite the port like so:
```
<soapProxy wsdl="http://wsdr.test.mc/wsDataRecord.asmx?wsdl" **port="8080"**>
</soapProxy>
```
