### ISSUE TITLE
idtoken is JWT, but missing the "typ":"JWT" field in the header

### ISSUE THREAD

**Issue by rrayst** [membrane/service-proxy#292]

**Comment by xorpherion** [comment]
https://tools.ietf.org/html/rfc7519#section-5.1
and
https://tools.ietf.org/html/rfc7515#section-4.1.9
specifically: `Use of this Header Parameter is OPTIONAL.`  in both

This is only needed when there is more than one type, but we only issue idtokens as JWT.

The "typ" field will be included in the next release.
