### ISSUE TITLE
fix oauth2 doc

### ISSUE THREAD

**Issue by rrayst** [membrane/service-proxy#293]
https://www.membrane-soa.org/service-proxy-doc/4.4/oauth2-code-flow-example.htm refers to :7000 but :2000 is correct

**Comment by rrayst** [comment]
in step 4 instead of ":2000", ":2001" should be used.

**Comment by MartinX3** [comment]
I looked into the current release 4.5 and checked the documentation on membrane-soa.org and the named ports in the text matched the ports written in the proxies.xml.

Did I miss something?
