### ISSUE TITLE
ConditionalInterceptor does not handle response

### ISSUE THREAD

**Issue by xorpherion** [membrane/service-proxy#308]

**Comment by rrayst** [comment]
This is a feature. The condition is evaluated once (in the request chain). As interceptors are executed, they are pushed on the interceptor stack.

For responses, the interceptor stack is simply being unwound while each interceptor is executed.

**Comment by xorpherion** [comment]
http://www.membrane-soa.org/service-proxy-doc/4.4/configuration/reference/if.htm

> Note that this is a draft implementation only: Design decissions are still pending.

> 'evaluate condition always during request handling already' (even when 'if' is nested in 'response')

I had a nested conditional interceptor in a response interceptor and i think that this case should be handled as interceptors are not pushed on the stack (because there was no handleRequest(...) call)
