### ISSUE TITLE
Throwing TypeRefAccessException

### ISSUE THREAD

**Issue by JMall0104** [membrane/service-proxy#317]
Hi All,

I have just started using Membrane. After I have set up and attempted to execute Membrane, I am getting an exception "TypeRefAccessException" (partially shown below).

Exception in thread "main" com.predic8.soamodel.TypeRefAccessException: Could not find the referenced type 'ArrayOfint' in namespace 'http://schemas.microsoft.com/2003/10/Serialization/Arrays'.

To be honest, I am not sure what I am doing wrong, or maybe I am failing to understand the content of my WSDL.

This is the command I am executing:
wsdldiff "http://www.test.com/MyService/Services/Service.svc?wsdl" "http://www.test.com/MyService2/Services/Service.svc?wsdl" C:\TestFolder

**Comment by rrayst** [comment]
This is not the ``service-proxy`` project, but https://github.com/membrane/soa-model/ . The error seems to be related to the schemas you are using. Please provide more details, if possible. Without the schemas, this is difficult to diagnose.
