### ISSUE TITLE
Failing Unit Test cases in service-proxy-core due to wrong HTTP Status code

### ISSUE THREAD

**Issue by precoder** [membrane/service-proxy#323]
It seems like for some unauthorized requests Membrane Authorization Server returns a wrong HTTP Status code.
There are 42 Failing Test which are expecting HTTP Status code 303 but get 307.

**Comment by precoder** [comment]
Here is the Full List of failing unit tests:

Failed tests:   test[testOpenidScopeButIsTokenResponseType](com.predic8.membrane.core.interceptor.oauth2.AuthWithoutSessionOpenidRequestTest): expected:<303> but was:<307>
  test[testHasClaimsButIsNotOpenid](com.predic8.membrane.core.interceptor.oauth2.AuthWithoutSessionOpenidRequestTest): expected:<303> but was:<307>
  test[testPromptEqualsLogin](com.predic8.membrane.core.interceptor.oauth2.AuthWithSessionRequestTest): expected:<303> but was:<307>
  test[testPromptEqualsNone](com.predic8.membrane.core.interceptor.oauth2.AuthWithSessionRequestTest): expected:<303> but was:<307>
  test[testPromptValueUnknown](com.predic8.membrane.core.interceptor.oauth2.AuthWithSessionRequestTest): expected:<303> but was:<307>
  test[testResponseTypeMissing](com.predic8.membrane.core.interceptor.oauth2.AuthWithoutSessionRequestTest): expected:<303> but was:<307>
  test[testScopeMissing](com.predic8.membrane.core.interceptor.oauth2.AuthWithoutSessionRequestTest): expected:<303> but was:<307>
  test[testPromptIsNone](com.predic8.membrane.core.interceptor.oauth2.AuthWithoutSessionRequestTest): expected:<303> but was:<307>
  test[testUnsupportedResponseType](com.predic8.membrane.core.interceptor.oauth2.AuthWithoutSessionRequestTest): expected:<303> but was:<307>
  test[testEmptyScopeList](com.predic8.membrane.core.interceptor.oauth2.AuthWithoutSessionRequestTest): expected:<303> but was:<307>
  test[testCodeResponse](com.predic8.membrane.core.interceptor.oauth2.EmptyEndpointTest): expected:<303> but was:<307>
  test[testTokenResponse](com.predic8.membrane.core.interceptor.oauth2.EmptyEndpointTest): expected:<303> but was:<307>
  test[testUnsupportedResponseType](com.predic8.membrane.core.interceptor.oauth2.EmptyEndpointTest): expected:<303> but was:<307>
  test[testConsentNotGiven](com.predic8.membrane.core.interceptor.oauth2.EmptyEndpointOpenidTest): expected:<303> but was:<307>
  test[testIdTokenTokenResponse](com.predic8.membrane.core.interceptor.oauth2.EmptyEndpointOpenidTest): expected:<303> but was:<307>
  test[testGoodAuthRequest](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorNormalTest): expected:<303> but was:<307>
  test[testGoodGrantedAuthCode](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorNormalTest): expected:<303> but was:<307>
  test[testGoodTokenRequest](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorNormalTest): expected:<303> but was:<307>
  test[testGoodUserinfoRequest](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorNormalTest): expected:<303> but was:<307>
  test[testGoodRevocationRequest](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorNormalTest): expected:<303> but was:<307>
  test[testGoodAuthRequest](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorOpenidTest): expected:<303> but was:<307>
  test[testGoodGrantedAuthCode](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorOpenidTest): expected:<303> but was:<307>
  test[testGoodTokenRequest](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorOpenidTest): expected:<303> but was:<307>
  test[testGoodUserinfoRequest](com.predic8.membrane.core.interceptor.oauth2.OAuth2AuthorizationServerInterceptorOpenidTest): expected:<303> but was:<307>
  test[testTokenMissing](com.predic8.membrane.core.interceptor.oauth2.RevocationRequestTest): expected:<303> but was:<307>
  test[testClientIdMissing](com.predic8.membrane.core.interceptor.oauth2.RevocationRequestTest): expected:<303> but was:<307>
  test[testClientSecretMissing](com.predic8.membrane.core.interceptor.oauth2.RevocationRequestTest): expected:<303> but was:<307>
  test[testWrongToken](com.predic8.membrane.core.interceptor.oauth2.RevocationRequestTest): expected:<303> but was:<307>
  test[testWrongCredentialsClientId](com.predic8.membrane.core.interceptor.oauth2.RevocationRequestTest): expected:<303> but was:<307>
  test[testWrongCredentialsClientId](com.predic8.membrane.core.interceptor.oauth2.RevocationRequestTest): expected:<303> but was:<307>
  test[testCodeMissing](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testClientIdMissing](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testClientSecretMissing](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testRedirectUriMissing](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testNoSessionForCode](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testInvalidClient](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testUnauthorizedClient](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testRedirectUriNotAbsolute](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testRedirectUriNotEquals](com.predic8.membrane.core.interceptor.oauth2.TokenRequestTest): expected:<303> but was:<307>
  test[testAuthorizationHeaderMissing](com.predic8.membrane.core.interceptor.oauth2.UserinfoRequestTest): expected:<303> but was:<307>
  test[testEmptyAuthorizationHeader](com.predic8.membrane.core.interceptor.oauth2.UserinfoRequestTest): expected:<303> but was:<307>
  test[testWrongTokenInAuthorizationHeader](com.predic8.membrane.core.interceptor.oauth2.UserinfoRequestTest): expected:<303> but was:<307>

**Comment by xorpherion** [comment]
Hi @precoder 
Thanks for you report. I am aware of the change from 303 to 307 statuscode (because 307 is more flexible and also allows other request types than GET). So the tests aren't up to date anymore and need to be changed to 307.

**Comment by precoder** [comment]
Oh that's a pity I have just made a fixed the code and pushed to make a pull request.
I should have open the issue first :)

If only thing to change is updating the status codes on the test cases then I can change them from 303 to 307 and make another pull request.

We want to make one more pull request for fixing errors related with Membrane Authorization Client and Server but before that we only wanted to be sure we are not breaking any other things.

**Comment by precoder** [comment]
Is there any change to merge the changes I provided under pull request 325 for fixing unit tests or is something missing there?
