### ISSUE TITLE
Update and correct slf4j version in pom.xml

### ISSUE THREAD

**Issue by LarsTor** [membrane/service-proxy#333]
Please update and correct slf4j version configurations in pom.xml.

1. Update to the latest slf4j version available: 1.7.13 (Nov, 2015) -> 1.7.25 (Mar, 2017)
```
<slf4j.version>1.7.13</slf4j.version>
```
-->
```
<slf4j.version>1.7.25</slf4j.version>
```

2. Correct the dependency

```
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j</artifactId>
	<version>1.7.21</version>
</dependency>
```
-->
```
...
	<version>${slf4j.version}</version>
...
```

3. Correct slf4j-ext-1.6.3.jar in distribution

Please check and correct why slf4j-ext in version 1.6.3 is included in membrane-service-proxy-4.6.2.zip and not version 1.7.13 (or now 1.7.25).

**Comment by rrayst** [comment]
Has been fixed by upgrading the io.swagger dependencies: slf4j* is now at 1.7.30 .
