### ISSUE TITLE
Incomplete XML to JSON transformation: xml2json.xsl does not take into account arrays.

### ISSUE THREAD

**Issue by sebastiandg7** [membrane/service-proxy#343]
Doing some test with the rest2soap interceptor I figured out that the current xml2json.xls transformation does not take into account array elements. Take a look at the next example:

If the xml body recevied from the SOAP service is:

```xml
<name>User's name</name>
<lastname>User's lastname</lastname>
<phone>
  <type>Personal</type>
  <number>1234567890</number>
</phone>
<phone>
  <type>Work</type>
  <number>1112223334</number>
</phone>
<phone>
  <type>Home</type>
  <number>9994446662</number>
</phone>
```
The converted JSON should be:
```json
{
  "name": "User's name",
  "lastname": "User's lastname",
  "phone": [
    {
      "type": "Personal",
      "number": "1234567890"
    },
    {
      "type": "Work",
      "number": "1112223334"
    },
    {
      "type": "Home",
      "number": "9994446662"
    }
  ]
}
````

The current transformation shows:
```json
{
  "name": "User's name",
  "lastname": "User's lastname",
  "phone":  {
      "type": "Home",
      "number": "9994446662"
  }
}
````
Using **the last <phone> incidence** to populate the "phone" JSON property.

Fixing the xml2json.xls to take into account this use case is the proper solution. Additionally giving the option to pass a custom xml2json.xls transformation file would also be helpful.

**Comment by sebastiandg7** [comment]
To address this in the current membrane-service-proxy version, as the moment of writing this is 4.6.2, I replaced the xml2json.xls in the **service-proxy-core-4.6.2.jar** located at service-proxy-core-4.6.2.jar\com\predic8\membrane\core\interceptor\rest.

**Comment by predic8** [comment]
@sebastiandg7 can you create a pull request with a fixed stylesheet?
