### ISSUE TITLE
WDSLInterceptor does'nt rewrite the url in attribute "location" of "wsdl:import" tag

### ISSUE THREAD

**Issue by yvesgrill** [membrane/service-proxy#344]
As I have to handle a wsdl that has a wsdl:import directive, I notice that the url of the location attribute is not rewrite. So I patch the class com.predic8.membrane.core.interceptor.WSDLInterceptor with the following line : 		
relocator.getRelocatingAttributes().put(
				new QName("http://schemas.xmlsoap.org/wsdl/", "import"), "location");
in the method "protected void rewrite(Exchange exc)".
This patch seems to correct the issue.

**Comment by predic8** [comment]
Can you create a pull request with the patch please?
