### ISSUE TITLE
Path traversal vulnerability

### ISSUE THREAD

**Issue by precoder** [membrane/service-proxy#353]
Hello,

We came across with 2 possible attacking vector report from a penetration test tool, which was running against all open ports.
This is possible if the WebServerInterceptor is activated.
Attacker can gain read only access to files system by giving an URL with 2 different ways:
1) an URL that has enough ..\\..\\ to move to root path (/ or C:) and then absolute path of the file
2) if files are served under a relative path, directly giving file:// with absolute path directly works, such as /path-prefx/file:// (linux) or  /path-prefx/file:\ (windows)

They are related with the CWE-23 and CWE-36
https://cwe.mitre.org/data/definitions/23.html
https://cwe.mitre.org/data/definitions/36.html

We could reproduce it with following requests:

1) CWE-23
Linux:
curl -k https://localhost:8080/..\\..\\..\\..\\..\\..\\..\\..\\etc/passwd
Windows:
curl http://localhost:8080/..\\..\\..\\..\\..\\..\\Windows\System32\drivers\etc\hosts

2) CWE-36
Linux:
curl http://localhost:8080/file:///etc/passwd
Windows:
curl http://localhost:8080/file://C:/temp/test.txt

Note: I could reproduce it also without /path-prefix under Windows but did not try on Linux.

I have used following proxies.xml section:
`
<serviceProxy name="Attack-Test" port="8080">
  <path>/</path>
    <webServer docBase="../../client" index="index.html"/>
</serviceProxy>
`
Calling URL on browser may fail since browser sometimes encodes chars or removes ..\\ but on the server it is processed.
I will provide a pull request as well for this problem on the WebServerInterceptor class.

**Comment by rrayst** [comment]
Thanks for the description and the pull request. It's already merged and the fixed version (4.7.3) is out. Maven Dependencies should be published within the next few hours.

**Comment by precoder** [comment]
Thank you very much for your very quick response.
