### ISSUE TITLE
Provide ability to flush DNS cache or hookup a custom DNS cache provider

### ISSUE THREAD

**Issue by dhruvchandna** [membrane/service-proxy#370]
Currently the `Router` initializes a `DNSCache` and that cache lives on for the life of the JVM. Can we provide a way to do one of the following:

- Provide means to flush the existing DNS Cache
- Enable / Disable DNS Cache using configuration
- Provide a custom DNS Cache implementation 

We encounter issues where we make changes to our infrastructure and the membrane has to be restarted in order to pick up the changes. We would like membrane to honor the TTL for a DNS and then flush its DNS cache or provide means by which we could provide a custom implementation.

**Comment by predic8** [comment]
Hi,
thanks for the issue and your ideas. We will consider that shortly and come back to you.
Thomas

**Comment by rrayst** [comment]
Unfortunately, there is no way to get the DNS TTL in Java (aside from re-implementing a full DNS resolver).

Starting with ``master`` (or any future release cut from the ``master`` branch), you could use

```
        <serviceProxy>
            <path>/clear</path>
            <groovy>
                spring.getBean("router").dnsCache.clear();
                Response.ok().build()
            </groovy>
        </serviceProxy>
```

(Note, however, that clearing the DNS cache has a performance impact on the next HTTP request for each target, of course.)
