### ISSUE TITLE
JWT Auth Interceptor

### ISSUE THREAD

**Issue by xorpherion** [membrane/service-proxy#371]
We should implement an interceptor that is capable of validating HS... and RS... alg JWTs. The claims could then be made available similar to how it is done with OAuth2

```
<groovy>
    def jwt = exc.properties.jwt
    <!-- Put the eMail into the header X-EMAIL and pass it to the protected server. -->
    exc.request.header.setValue('X-EMAIL',jwt.email)
    CONTINUE
</groovy>

```

**Comment by rrayst** [comment]
the key(s) to verify the signature 
* could be specified in-place (as we do with the ``//jwtSessionManager/jwt`` either inline or using the ``@location`` attribute)
* could be downloaded from an OIDC Discovery ``jwks_uri``

**Comment by rrayst** [comment]
* expected audience field should be specifiable
