### ISSUE TITLE
Is there a Release Plan for 4.8.9?

### ISSUE THREAD

**Issue by precoder** [membrane/service-proxy#389]
Hello,

Correct me if I am wrong, I remember some information about moving to continues delivery for the Membrane Service Proxy Project for SaaS and old kind of on premise releases may not happen very frequently.

Do you still have a fixed release Plan for the upcoming 4.8.9 version with Spring dependencies 5.x,?
We would like to use it when it is available.

**Comment by rrayst** [comment]
Release is out, sorry for the delay: https://github.com/membrane/service-proxy/releases/tag/v4.8.10

Moving to continous delivery sounds interesting, but we do not have the capacity to realize that at the moment.

**Comment by precoder** [comment]
Thank you very much for the information and for the new Release :)
