### ISSUE TITLE
HTTP PROPFIND not supported properly

### ISSUE THREAD

**Issue by minibiti** [membrane/service-proxy#394]
Hi,

I am trying to use the service-proxy to reach a SVN server via HTTP.
The local client talks HTTP to the Membrane service proxy, which in turns talks https to the SVN server.
Here is my config (for some reasons the XML below does not display in read mode so I removed a few > or <...):
		serviceProxy port="7777">
			target host="svn.myserver.com" port="443">
		                ssl ignoreTimestampCheckFailure="true" />
			</target 
		</serviceProxy

It works fine from the browser, when I go against localhost:7777, but from the svn CLI it fails:
$ svn co http://localhost:7777/svn/somerepo/
svn: E175002: Unexpected HTTP status 400 'Bad Request' on '/svn/!svn/vcc/default'

On the Statistics page in the Membrane admin console, I see that we get status code 207 for the PROPFIND method.

In the shell where I started the server, I see this:
ERROR 22 RouterThread /127.0.0.1:46062 Header:149 - Header read line that caused problems: 0

Any idea/quick fixes?

At first I tried with service-proxy v4.8.7 and then it was just hanging forever.
Now I am using v4.9.1 and I get this error.

I have cloned the repo and compiled the code locally. Let me know if you want me to try something :)

**Comment by rrayst** [comment]
Hi @minibiti , can you attach your proxies.xml ? Thanks, Toby

**Comment by minibiti** [comment]
Sure, here it is.
I just change the name of the server I go against to svn.someserver.com.
I had to zip it as XML was not accepted.
[proxies.zip](https://github.com/membrane/service-proxy/files/10098221/proxies.zip)

I had a look in the Header.java class and tried to add a "continue" if (line.equals("0")), but it did not help. Just failed later without any output...

**Comment by minibiti** [comment]
Is there anything I can try locally to get the PROPFIND requests working? I am a bit lost in your code base but I can run snapshot versions locally from the github code.
