### ISSUE TITLE
Current 5.0.0 release does not start 

### ISSUE THREAD

**Issue by koin612** [membrane/service-proxy#421]
Missing `./conf/fruitshop-api.yml` stops membrane boot

> Membrane Router running...
> 11:41:18,202  INFO 1 main OpenAPIRecordFactory:78 - Parsing spec fruitshop-api.yml
> org.springframework.context.ApplicationContextException: Failed to start bean 'router'
> 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
> 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
> 	at org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:103)
> 	at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1416)
> 	at com.predic8.membrane.core.Router.init(Router.java:159)
> 	at com.predic8.membrane.core.RouterCLI.main(RouterCLI.java:48)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at com.predic8.membrane.core.Starter.main(Starter.java:49)
> Caused by: java.lang.RuntimeException: com.predic8.membrane.core.resolver.ResourceRetrievalException: java.io.FileNotFoundException: /Users/niko/Downloads/membrane-service-proxy-5.0.0/conf/fruitshop-api.yml (No such file or directory) while retrieving file:/Users/niko/Downloads/membrane-service-proxy-5.0.0/conf/fruitshop-api.yml
> 	at com.predic8.membrane.core.Router.start(Router.java:312)
> 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
> 	... 12 more
> Caused by: com.predic8.membrane.core.resolver.ResourceRetrievalException: java.io.FileNotFoundException: /Users/niko/Downloads/membrane-service-proxy-5.0.0/conf/fruitshop-api.yml (No such file or directory) while retrieving file:/Users/niko/Downloads/membrane-service-proxy-5.0.0/conf/fruitshop-api.yml
> 	at com.predic8.membrane.core.resolver.FileSchemaResolver.resolve(FileSchemaResolver.java:76)
> 	at com.predic8.membrane.core.resolver.ResolverMap.resolve(ResolverMap.java:198)
> 	at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIRecordFactory.getInputStreamForLocation(OpenAPIRecordFactory.java:116)
> 	at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIRecordFactory.getOpenAPI(OpenAPIRecordFactory.java:106)
> 	at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIRecordFactory.create(OpenAPIRecordFactory.java:94)
> 	at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIRecordFactory.addOpenApisFromLocation(OpenAPIRecordFactory.java:79)
> 	at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIRecordFactory.create(OpenAPIRecordFactory.java:51)
> 	at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIProxy.initOpenAPI(OpenAPIProxy.java:143)
> 	at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIProxy.init(OpenAPIProxy.java:136)
> 	at com.predic8.membrane.core.rules.AbstractProxy.init(AbstractProxy.java:166)
> 	at com.predic8.membrane.core.Router.initRemainingRules(Router.java:278)
> 	at com.predic8.membrane.core.Router.init(Router.java:272)
> 	at com.predic8.membrane.core.Router.start(Router.java:297)
> 	... 13 more
> Caused by: java.io.FileNotFoundException: /Users/niko/Downloads/membrane-service-proxy-5.0.0/conf/fruitshop-api.yml (No such file or directory)
> 	at java.base/java.io.FileInputStream.open0(Native Method)
> 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
> 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
> 	at com.predic8.membrane.core.resolver.FileSchemaResolver.resolve(FileSchemaResolver.java:74)
> 	... 25 more

**Comment by rrayst** [comment]
fixed with release v5.0.1
