### ISSUE TITLE
regexReplacer MIME exclusion list insufficient, can corrupt binary data

### ISSUE THREAD

**Issue by aarismendi** [membrane/service-proxy#437]
Hi, I posted about this in the google discussion group but I think it's worth creating an issue here. I recently tried the regexReplacer on a serviceProxy for responses and found that it was corrupting zip data that came back from an API call. The server response MIME type was application/zip however the current check to exclude binary traffic does not exclude that mime type. There are also other MIME types that are binary which are not excluded. It would be great to provide a whitelisting MIME type parameter to regexReplacer similar to what httpd mod_substitute does so only the MIME types that need to be regexed are processed.

Example for httpd: AddOutputFilterByType SUBSTITUTE text/html text/plain text/xml text/css
https://httpd.apache.org/docs/2.4/mod/mod_substitute.html

**Comment by predic8** [comment]
Hi @aarismendi,
thanks for creating the issue. We'll have a look at it shortly. Maybe we have to decode the transport encoding (zip or gzip) for the regexReplacer, so that compressed messages are also processed.
Instead of whitelisting it might be possible to use an if-interceptor like:

<if condition="<<not MIME Type xyz">
   <regexReplacer>...
</if>

**Comment by aarismendi** [comment]
Ok great, thank you! To clarify in this case the response from the API was an actual zip file (API name is generateZip) rather than gzip'd text as is done with static content compression so the regexReplacer should never attempt to process it.

**Comment by predic8** [comment]
@aarismendi I created a pull request that adds application/zip to the binary types. I guess we will release version 5.1.0 in about 3-4 weeks with the fix.

**Comment by aarismendi** [comment]
Ok great, thank you! May want to consider implementing a whitelisting feature in the future because based on the current list of mime types there are others that are binary that aren't excluded and could cause problems - https://www.iana.org/assignments/media-types/media-types.xhtml.

**Comment by predic8** [comment]
We are between two solutions whitelist or an example how to do that with an <if> element in the proxies.xml. The condition has the advantage that we do not mix responsibilities.
