### ISSUE TITLE
dynamica proxies.xml to config center

### ISSUE THREAD

**Issue by a844306539** [membrane/service-proxy#520]
Currently every time you deploy a project, I need to manually update the proxies.xml, if I need to dynamically get the configuration from a configuration center, such as apollo configuration center, I only need to modify the init method of Route？

**Comment by predic8** [comment]
Hi,
I'am not sure if I understand your problem. Maybe it would be useful if you make a concrete example. 
To update an installation we keep the old proxies.xml file and just copy it into a new Docker Container or we copy it into a new installation using a configuration management tool like Ansible. Perhaps this would also work in your setup?
Cheers
Thomas

**Comment by a844306539** [comment]
I now need to deploy service-proxy in different environments, in no environment my proxies .xml different, my current practice is update proxies.xml and to repackage every time I rebuild, I want to make dynamic changes

**Comment by a844306539** [comment]
![image](https://user-images.githubusercontent.com/33318972/231342685-fedcd530-ec5b-4142-a0af-748d3f6c679b.png)
![image](https://user-images.githubusercontent.com/33318972/231344042-cae937db-0f01-4a05-bfa5-bf81ac2a2334.png)


I change console page to add a refresh method , this method receive proxies.xml config and output file to configuration file location, use HotDeploymentThread compeleted dynamic load.

I don't know if that's a reasonable approach；

**Comment by predic8** [comment]
Hi, that works technically. But we recommend to solve it using DevOps and GitOps practices. Put the configuration into git, create a pipeline that deploys Membrane from git. When you change configuration you start a new Membrane either in a container or as process. To be high available use two instacnes.

**Comment by a844306539** [comment]
ok thanks
