### ISSUE TITLE
Context path missing from WSDL endpoint

### ISSUE THREAD

**Issue by chrisheyne** [membrane/service-proxy#59]
Version 3.5.7 deployed to Websphere 8
The context path is missing from rewritten WSDL endpoints. 

Example scenario --

Membrane web application deployed at /services

Configuration element -- 

``` xml
    <soapProxy wsdl="http://test/services/2.1/Service/Service.wsdl" >   
        <path>/test_service</path>
        <log/>
    </soapProxy>
```

Membrane makes the WSDL available at /services/test_service?wsdl

Expected Result --
Endpoint paths in WSDL are rewritten as '/services/test_service'

Actual Result --
Endpoint paths in WSDL are rewritten as '/test_service'

**Comment by rrayst** [comment]
verified in master
