### ISSUE TITLE
WSDLREWRITER: if port=80 leave port blank

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#61]
The rewriter produces:

    <wsdl:port name="KundenAdrImportPort" binding="tns:KundenAdrImportBinding">
    <soap:address location="http://berlin.local:80/services/KundenAdrImport"/>
    </wsdl:port>

but should:

    <wsdl:port name="KundenAdrImportPort" binding="tns:KundenAdrImportBinding">
    <soap:address location="http://berlin.local/services/KundenAdrImport"/>
    </wsdl:port>

same with https and 443

**Comment by rrayst** [comment]
already fixed in master
