### ISSUE TITLE
Failed tests in OpenAPI scope

### ISSUE THREAD

**Issue by koin612** [membrane/service-proxy#728]
These tests currently fail on build:

- OpenAPIInterceptorTest
- OpenAPIValidatorObjectTest
- ResponseTest
- NestedObjectArrayTest

**Comment by predic8** [comment]
Fixed them. Should be this afternoon in the master.

Von: Niko ***@***.***>
Antworten an: membrane/service-proxy ***@***.***>
Datum: Mittwoch, 13. September 2023 um 10:35
An: membrane/service-proxy ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [membrane/service-proxy] Failed tests in OpenAPI scope (Issue #728)


These tests currently fail on build:
·         OpenAPIInterceptorTest
·         OpenAPIValidatorObjectTest
·         ResponseTest
·         NestedObjectArrayTest

**Comment by koin612** [comment]
fixed with #731 there also was #730 a few minutes earlier, but I think #730 only fixes currently broken tests and not every validator like tried in #731. Discussion was opened in the PR.
